[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pydeepspeech"
version = "0.0.4"
description = "Mozilla's DeepSpeech transcriber in a pip installable package."
readme = "README.md"
license = "MIT"
requires-python = ">=3.7.0"
authors = [
    { name = "Zach Vorhies", email = "dont@email.me" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
]
dependencies = [
    "capturing_process",
    "requests==2.31.0",
    "deepspeech",
    "pathlib",
    "webrtcvad",
]


[tool.hatch.metadata]
allow-direct-references = true


[project.optional-dependencies]
test = [
    "pytest",
]


[project.scripts]
pydeepspeech = "pydeepspeech.run:main"
pydeepspeech_installmodels = "pydeepspeech.interactive_install_modules:main"


[project.urls]
Homepage = "https://github.com/zackees/pydeepspeech"


[tool.hatch.build.targets.sdist]
include = [
    "/pydeepspeech",
]
